SELECT 
  DISTINCT UPPER(TRIM(VEHICLE_MAKE)) AS VEHICLE_MAKE
FROM `ferrous-thought-409502.insurance.vehicles`
WHERE
  `CRASH_DATE` BETWEEN '2020-01-01' AND '2024-12-01'
  AND `VEHICLE_TYPE` IS NOT NULL
  AND TRIM(UPPER(`VEHICLE_TYPE`)) <> ''
  AND (UPPER(`VEHICLE_TYPE`) LIKE "%MOTORCYCLE%"
  OR UPPER(`VEHICLE_TYPE`) LIKE "%MOPED"
  OR UPPER(`VEHICLE_TYPE`) = "MOTORBIKE")
  AND DRIVER_SEX IS NOT NULL
  AND DRIVER_LICENSE_STATUS IS NOT NULL
  AND VEHICLE_MAKE IS NOT NULL
  AND COLLISION_ID IS NOT NULL
GROUP BY
  VEHICLE_MAKE
