SELECT 
  COUNT(DISTINCT COLLISION_ID) AS number_of_collisions, 
  LEAST(TRIM(UPPER(`ON STREET NAME`)), TRIM(UPPER(`CROSS STREET NAME`))) AS primary_street_name,
  GREATEST(TRIM(UPPER(`ON STREET NAME`)), TRIM(UPPER(`CROSS STREET NAME`))) AS secondary_street_name,
  (SELECT COUNT (*) 
  FROM `ferrous-thought-409502.insurance.crashes` 
  ) AS total_accidents
FROM 
  `ferrous-thought-409502.insurance.crashes`
WHERE
  BOROUGH IS NOT NULL
  AND `ZIP CODE` IS NOT NULL
  AND `ZIP CODE` >10000
  AND LATITUDE IS NOT NULL
  AND LONGITUDE IS NOT NULL
  AND `ON STREET NAME` IS NOT NULL
  AND `CROSS STREET NAME` IS NOT NULL
  AND TRIM(UPPER(`ON STREET NAME`)) <> ''
  AND TRIM(UPPER(`CROSS STREET NAME`)) <> ''
  AND TRIM(UPPER(`CROSS STREET NAME`)) <> TRIM(UPPER(`ON STREET NAME`))
  AND TRIM(UPPER(`ON STREET NAME`)) <> TRIM(UPPER(`CROSS STREET NAME`))

GROUP BY
  LEAST(TRIM(UPPER(`ON STREET NAME`)), TRIM(UPPER(`CROSS STREET NAME`))), 
  GREATEST(TRIM(UPPER(`ON STREET NAME`)), TRIM(UPPER(`CROSS STREET NAME`)))
ORDER BY
  COUNT(DISTINCT COLLISION_ID) DESC

  