WITH cleaned_vehicles AS (
    SELECT 
        COLLISION_ID,
        DRIVER_LICENSE_STATUS,
        VEHICLE_TYPE,
        DRIVER_SEX,
        CASE 
            WHEN UPPER(TRIM(VEHICLE_MAKE)) LIKE '%HONDA%' THEN 'HONDA'
            WHEN UPPER(TRIM(VEHICLE_MAKE)) LIKE '%YAMA%' THEN 'YAMAHA'
            WHEN UPPER(TRIM(VEHICLE_MAKE)) LIKE '%SUZU%' THEN 'SUZUKI'
            WHEN UPPER(TRIM(VEHICLE_MAKE)) LIKE '%HARLEY%' THEN 'HARLEY DAVIDSON'
            WHEN UPPER(TRIM(VEHICLE_MAKE)) LIKE '%KAWAS%' THEN 'KAWASAKI'
            WHEN UPPER(TRIM(VEHICLE_MAKE)) LIKE '%BMW%' THEN 'BMW'
            WHEN UPPER(TRIM(VEHICLE_MAKE)) LIKE '%DUCAT%' THEN 'DUCATI'
            WHEN UPPER(TRIM(VEHICLE_MAKE)) LIKE '%VES%' THEN 'VESPA'
            WHEN UPPER(TRIM(VEHICLE_MAKE)) LIKE '%MOPED%' THEN 'UNKNOWN'
            WHEN UPPER(TRIM(VEHICLE_MAKE)) LIKE '%MOTORCYCLE%' THEN 'UNKNOWN'
            WHEN UPPER(TRIM(VEHICLE_MAKE)) IS NULL OR UPPER(TRIM(VEHICLE_MAKE)) = '' THEN 'UNKNOWN'
            ELSE 'OTHER'
        END AS CLEANED_VEHICLE_MAKE
    FROM `ferrous-thought-409502.insurance.vehicles`
    WHERE 
        `CRASH_DATE` BETWEEN '2020-01-01' AND '2024-12-01'
        AND `VEHICLE_TYPE` IS NOT NULL
        AND TRIM(UPPER(`VEHICLE_TYPE`)) <> ''
        AND (UPPER(`VEHICLE_TYPE`) LIKE "%MOTORCYCLE%"
        OR UPPER(`VEHICLE_TYPE`) LIKE "%MOPED"
        OR UPPER(`VEHICLE_TYPE`) = "MOTORBIKE")
        AND DRIVER_SEX IS NOT NULL
        AND DRIVER_LICENSE_STATUS IS NOT NULL
        AND VEHICLE_MAKE IS NOT NULL
        AND COLLISION_ID IS NOT NULL
)

SELECT 
    DRIVER_LICENSE_STATUS,
    VEHICLE_TYPE,
    CLEANED_VEHICLE_MAKE,
FROM cleaned_vehicles
GROUP BY 
    DRIVER_LICENSE_STATUS,
    VEHICLE_TYPE,
    CLEANED_VEHICLE_MAKE

